sudo: required

language: rust

compiler:
    - gcc

before_install:
    - echo $LANG
    - echo $LC_ALL
    - if [ $TRAVIS_OS_NAME == linux ]; then git clone https://github.com/emoon/tundra.git; cd tundra; git checkout rust; make; sudo make install; cd ..; fi
    - if [ $TRAVIS_OS_NAME == linux ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
    - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update && sudo apt-get install -y libx11-dev libgl1-mesa-dev g++-4.9; fi
    - if [ $TRAVIS_OS_NAME == linux ]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 90; fi

script: tundra2 linux-gcc-debug 

os:
  - linux
