version: '{build}'
skip_tags: true
environment:
  matrix:
  - GENERATOR: Visual Studio 12 Win64
    DEPS_PATH: deps64
install: []
build_script:
- scripts\vcvarsx86_amd64.bat 
- scripts\win64_build_debug.cmd 
