[package]
name = "ui"
version = "0.1.0"
authors = ["Daniel Collin <daniel@collin.com>"]

[build-dependencies]
gcc = "0.3.19"

[dependencies]
libc = "0.2"
time = "0.1.34"

[target.x86_64-pc-windows-msvc.dependencies]
user32-sys = "0.1.2"
winapi = "0.2.4"
kernel32-sys = "0.1.4"
gdi32-sys = "0.1.1"

[target.x86_64-pc-windows-gnu.dependencies]
user32-sys = "0.1.2"
winapi = "0.2.4"
kernel32-sys = "0.1.4"
gdi32-sys = "0.1.1"

[target.i686-pc-windows-msvc.dependencies]
user32-sys = "0.1.2"
winapi = "0.2.4"
kernel32-sys = "0.1.4"
gdi32-sys = "0.1.1"

[target.i686-pc-windows-gnu.dependencies]
user32-sys = "0.1.2"
winapi = "0.2.4"
kernel32-sys = "0.1.4"
gdi32-sys = "0.1.1"

[target.i686-unknown-linux-gnu.dependencies]
x11-dl = "~2.2"

[target.x86_64-unknown-linux-gnu.dependencies]
x11-dl = "~2.2"

[target.arm-unknown-linux-gnueabihf.dependencies]
x11-dl = "~2.2"

[target.aarch64-unknown-linux-gnu.dependencies]
x11-dl = "~2.2"

[target.x86_64-unknown-dragonfly.dependencies]
x11-dl = "~2.2"

[target.x86_64-unknown-freebsd.dependencies]
x11-dl = "~2.2"
